[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[override]]
  name = "gopkg.in/resty.v1"

[[override]]
  name = "github.com/jbogarin/go-cisco-webex-teams"
  revision = "758c23da78f5a12135cc49ca21a5286552fd9673"

[[override]]
  name = "github.com/go-chi/chi"
  branch = "~4.0.2"
